# Generated by Django 5.2.7 on 2025-10-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='low', help_text='Niveau de criticité automatique basé sur le type et la confiance', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
