# Generated by Django 4.2 on 2025-10-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityscenario',
            options={'ordering': ['name'], 'verbose_name': 'Scénario de sécurité', 'verbose_name_plural': 'Scénarios de sécurité'},
        ),
        migrations.AlterField(
            model_name='securityscenario',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='securityscenario',
            name='event_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
