# Generated by Django 5.2.7 on 2025-10-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_camera_owner_alter_controlcenter_owner'),
        ('Core', '0002_event_priority_event_snapshot'),
    ]

    operations = [
    ]
