# Generated by Django 5.2.7 on 2025-10-31 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_merge_20251030_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cameras', to='Core.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='events_snapshots/'),
        ),
    ]
